ProductionTypeBuilding: E
	Description: Building Tab
	Types: Production
	Contexts: Player

ProductionTypeDefense: R
	Description: Defense Tab
	Types: Production
	Contexts: Player

ProductionTypePods: T
	Description: Pods Tab
	Types: Production
	Contexts: Player

ProductionTypeVehicle: Y
	Description: Vehicle Tab
	Types: Production
	Contexts: Player

ProductionTypeAircraft: U
	Description: Aircraft Tab
	Types: Production
	Contexts: Player

ProductionTypeNaval: I
	Description: Naval Tab
	Types: Production
	Contexts: Player

ProductionTypeTrade: O
	Description: Trade Tab
	Types: Production
	Contexts: Player

ProductionTypeLightVehicles: K
	Description: Workers Tab
	Types: Production
	Contexts: Player

ToggleVariant: V
	Description: Rotate Building
	Types: Production
	Contexts: Player

PowerDown: X
	Description: Power-down mode
	Types: OrderGenerator
	Contexts: Player
