label-assetbrowser-title = Explorateur de ressources
label-assetbrowser-source-selector-desc = Sélectionner la source des ressources
dropdownbutton-assetbrowser-source-selector = Dossiers
dropdownbutton-assetbrowser-asset-types-dropdown = Types de ressources
label-assetbrowser-filename-desc = Filtrer par nom
label-assetbrowser-sprite-scale = Échelle :
label-assetbrowser-palette-desc = Palette :
label-assetbrowser-sprite-bg-error = Erreur d'affichage du fichier. Consultez assetbrowser.log pour plus de détails.
button-color-chooser-random = Aléatoire
button-color-chooser-store = Enregistrer
button-color-chooser-mixer-tab = Mélangeur
button-color-chooser-palette-tab = Panneau de construction
label-preset-header = Couleurs prédéfinies
label-custom-header = Couleurs personnalisées
button-prompt-confirm = Confirmer
button-prompt-other = Redémarrer
button-text-input-prompt-accept = OK
label-connectionfailed-panel-password = Mot de passe :
button-connectionfailed-panel-abort = Abandonner
label-connecting-panel-title = Connexion
button-connecting-panel-abort = Abandonner
label-connection-switchmod-panel-title = Changer de mod
label-connection-switchmod-panel-desc = Ce serveur exécute un mod différent :
label-connection-switchmod-panel-desc2 = Changer de mod et rejoindre le serveur ?
button-connection-switchmod-panel-switch = Changer
button-connection-switchmod-panel-abort = Abandonner
label-openra = OpenRA
label-credits-title = Crédits
label-new-map-bg-title = Nouvelle carte
label-new-map-bg-tileset = Jeu de tuiles :
label-new-map-bg-width = Largeur :
label-new-map-bg-height = Hauteur :
button-new-map-bg-create = Créer
label-save-map-panel-heading = Enregistrer la carte
label-save-map-panel-title = Titre :
label-save-map-panel-author = Auteur :
label-save-map-panel-visibility = Visibilité :
dropdownbutton-save-map-panel-visibility-dropdown = Visibilité de la carte
label-save-map-panel-directory = Répertoire :
label-save-map-panel-filename = Nom du fichier :
button-save-map-panel = Enregistrer
label-actor-edit-panel-id = ID
button-container-ok = OK
label-tiles-bg-search = Recherche :
label-bg-filter = Filtre :
label-actors-bg-search = Recherche :
label-area-selection = Sélection de zone
label-area-info = Infos de zone
label-selected-area-diagonal = Diagonale :
label-selected-area-resources = Ressources :
label-filter-terrain = Terrain
label-filter-resources = Ressources
label-filter-actors = Acteurs
button-marker-tiles-clear-current = Effacer l'actuel
button-marker-tiles-clear-all = Tout effacer
label-marker-layer-num-sides = Nombre de côtés
label-marker-alpha = Alpha des tuiles
label-marker-mirror-mode = Mode miroir
label-marker-axis-angle = Angle d'axe
button-map-editor-tab-container-select-tooltip = Sélectionner
button-map-editor-tab-container-tiles-tooltip = Tuiles
button-map-editor-tab-container-overlays-tooltip = Calques
button-map-editor-tab-container-actors-tooltip = Acteurs
button-map-editor-tab-container-tools-tooltip = Outils
button-map-editor-tab-container-history-tooltip = Historique
button-editor-world-root-options =
    .label = Menu
    .tooltip = Menu
dropdownbutton-editor-world-root-overlay-button = Calques
button-select-categories-buttons-all = Tous
button-select-categories-buttons-none = Aucun
label-tool-marker-tiles = Tuiles marqueurs
label-gamesave-browser-panel-load-title = Charger une partie
label-gamesave-browser-panel-save-title = Sauvegarder la partie
label-gamesave-browser-panel-title = { "[" }CRÉER UN NOUVEAU FICHIER]
button-gamesave-browser-panel-delete-all = Tout supprimer
button-gamesave-browser-panel-delete = Supprimer
button-gamesave-browser-panel-rename = Renommer
button-gamesave-browser-panel-load = Charger
button-gamesave-browser-panel-save = Sauvegarder
button-chat-chrome-mode =
    .label = Équipe
    .tooltip = Basculer le mode de chat
dropdownbutton-hpf-overlay-locomotor = Sélectionner le locomoteur
dropdownbutton-hpf-overlay-check = Sélectionner BlockedByActor
label-debug-panel-title = Options de débogage
checkbox-debug-panel-instant-build = Construction instantanée
checkbox-debug-panel-enable-tech = Tout construire
checkbox-debug-panel-build-anywhere = Construire partout
checkbox-debug-panel-unlimited-power = Énergie illimitée
checkbox-debug-panel-instant-charge = Temps de charge instantané
checkbox-debug-panel-disable-visibility-checks = Désactiver les vérifications de visibilité
button-debug-panel-give-cash = Donner 20 000 $
button-debug-panel-grow-resources = Faire pousser les ressources
button-debug-panel-give-exploration = Effacer le brouillard
button-debug-panel-reset-exploration = Réinitialiser le brouillard
label-debug-panel-visualizations-title = Visualisations
checkbox-debug-panel-show-unit-paths = Afficher les chemins des unités
checkbox-debug-panel-show-customterrain-overlay = Afficher le terrain personnalisé
checkbox-debug-panel-show-actor-tags = Afficher les tags des acteurs
checkbox-debug-panel-show-combatoverlay = Afficher la géométrie de combat
checkbox-debug-panel-show-geometry = Afficher la géométrie de rendu
checkbox-debug-panel-show-terrain-overlay = Afficher la géométrie du terrain
checkbox-debug-panel-show-screenmap = Afficher la carte écran
label-mission-objectives = Mission :
label-stats-player = Joueur
label-stats-faction = Faction
label-stats-score = Score
label-stats-actions = Actions
label-menu-buttons-title = Options
checkbox-kick-client-dialog-prevent-rejoining = Bannir temporairement
button-kick-client-dialog = Expulser
label-kick-spectators-dialog-title = Expulser les spectateurs
button-kick-spectators-dialog-ok = OK
label-force-start-dialog-title = Lancer la partie ?
label-kick-warning-a = Un ou plusieurs clients n'ont pas la carte sélectionnée
label-kick-warning-b = et seront expulsés du serveur.
button-force-start-dialog-start = Démarrer
label-map-incompatible-status-a = Cette carte n'est pas compatible
label-map-incompatible-status-b = avec cette version d'OpenRA
label-map-validating-status = Validation...
button-map-download-available-install = Installer la carte
button-map-preview-update = Mettre à jour la carte
button-map-update-download-available-install = Installer la carte
label-map-preview-searching = Recherche sur le Centre de Ressources OpenRA...
label-map-unavailable-a = Cette carte n'a pas été trouvée sur le
label-map-unavailable-b = Centre de Ressources OpenRA
label-map-preview-error = Une erreur s'est produite lors de l'installation
label-map-update-available-a = Une nouvelle version de la carte
label-map-update-available-b = a été trouvée sur votre ordinateur
label-music-controls-volume = Volume :
label-music-title = Musique
label-music-controls-length = Durée
checkbox-music-controls-shuffle = Aléatoire
checkbox-music-controls-loop = Boucle
label-container-title = Piste
label-no-music-title = Musique non installée
label-lobby-options-bin-title = Options de carte
label-lobby-players-name = Nom
label-lobby-players-color = Couleur
label-lobby-players-faction = Faction
label-lobby-players-team = Équipe
label-lobby-players-handicap = Handicap
label-lobby-players-spawn = Apparition
label-lobby-players-ready = Prêt
dropdownbutton-lobby-players-handicap-tooltip = Un handicap diminue l'efficacité au combat des forces du joueur
button-lobby-players-join = Jouer dans cet emplacement
label-lobby-players-spectator = Spectateur
checkbox-lobby-players-new-spectator-toggle = Autoriser les spectateurs ?
button-lobby-players-spectate = Observer
image-lobby-servers-bin-password-protected-tooltip = Nécessite un mot de passe
image-lobby-servers-bin-requires-authentication-tooltip = Nécessite un compte forum OpenRA
dropdownbutton-lobby-servers-bin-filters = Filtrer les parties
label-container-server = Serveur
label-container-players = Joueurs
label-container-location = Emplacement
label-container-status = Statut
label-notice-container-outdated-version = Vous utilisez une version obsolète d'OpenRA. Téléchargez la dernière version sur www.openra.net
label-notice-container-unknown-version = Vous utilisez une version non reconnue d'OpenRA. Téléchargez la dernière version sur www.openra.net
label-notice-container-playtest-available = Un aperçu de la prochaine version d'OpenRA est disponible pour test. Téléchargez la version test sur www.openra.net
dropdownbutton-server-lobby-slots = Admin des emplacements
button-server-lobby-reset-options = Réinitialiser les valeurs par défaut
button-skirmish-tabs-players-tab = Joueurs
button-skirmish-tabs-options-tab = Options
button-multiplayer-tabs-players-tab = Joueurs
button-multiplayer-tabs-options-tab = Options
button-multiplayer-tabs-servers-tab = Serveurs
button-server-lobby-changemap = Changer de carte
button-lobbychat-chat-mode =
    .label = Équipe
    .tooltip = Basculer le mode de chat
button-server-lobby-start-game = Lancer la partie
button-server-lobby-disconnect = Quitter la partie
label-mainmenu-introduction-prompt-title = Établissement du contrôle du champ de bataille
label-mainmenu-introduction-prompt-desc-a = Bon retour Commandant ! Initialisez les paramètres de combat avec les options ci-dessous.
label-mainmenu-introduction-prompt-desc-b = Des options supplémentaires peuvent être configurées plus tard depuis le menu Paramètres.
label-mainmenu-system-info-prompt-title = Établissement du contrôle du champ de bataille
label-mainmenu-system-info-prompt-text-a = Nous aimerions collecter certains détails système qui nous aideront à optimiser OpenRA.
label-mainmenu-system-info-prompt-text-b = Avec votre permission, les données anonymes suivantes seront envoyées à chaque lancement du jeu :
checkbox-mainmenu-system-info-prompt-sysinfo = Envoyer les informations système
label-profile-section-header = Profil
label-player-container = Nom du joueur :
label-playercolor-container-color = Couleur préférée :
label-display-section-header = Affichage
label-battlefield-camera-dropdown = Caméra du champ de bataille :
label-ui-scale-dropdown = Échelle de l'interface :
checkbox-cursordouble-container = Agrandir le curseur
label-input-section-header = Contrôles
label-mouse-control-container = Schéma de contrôle :
label-mouse-control-desc-classic-selection = - Sélectionner les unités avec le bouton <Gauche> de la souris
label-mouse-control-desc-classic-commands = - Donner des ordres aux unités avec le bouton <Gauche> de la souris
label-mouse-control-desc-classic-support = - Cibler les pouvoirs de soutien avec le bouton <Gauche> de la souris
label-mouse-control-desc-classic-zoom = - Zoomer sur le champ de bataille avec la <Molette>
label-mouse-control-desc-classic-zoom-modifier = - Zoomer sur le champ de bataille avec <MODIFICATEUR + Molette>
label-mouse-control-desc-classic-scroll-right = - Déplacer la vue avec le bouton <Droit> de la souris
label-mouse-control-desc-classic-scroll-middle = - Déplacer la vue avec le bouton <Central> de la souris
label-mouse-control-desc-classic-edgescroll = ou en déplaçant le curseur au bord de l'écran
label-mouse-control-desc-modern-selection = - Sélectionner les unités avec le bouton <Gauche> de la souris
label-mouse-control-desc-modern-commands = - Donner des ordres aux unités avec le bouton <Droit> de la souris
label-mouse-control-desc-modern-support = - Cibler les pouvoirs de soutien avec le bouton <Gauche> de la souris
label-mouse-control-desc-modern-zoom = - Zoomer sur le champ de bataille avec la <Molette>
label-mouse-control-desc-modern-zoom-modifier = - Zoomer sur le champ de bataille avec <MODIFICATEUR + Molette>
label-mouse-control-desc-modern-scroll-right = - Déplacer la vue avec le bouton <Droit> de la souris
label-mouse-control-desc-modern-scroll-middle = - Déplacer la vue avec le bouton <Central> de la souris
label-mouse-control-desc-modern-edgescroll = ou en déplaçant le curseur au bord de l'écran
checkbox-edgescroll-container = Défilement au bord de l'écran
label-singleplayer-title = Solo
button-extras-title = Extras
button-main-menu-content = Gérer le contenu
button-singleplayer-menu-skirmish = Escarmouche
button-singleplayer-menu-load = Charger
button-extras-menu-replays = Rediffusions
label-map-editor-title = Éditeur de carte
button-extras-menu-assetbrowser = Explorateur de ressources
button-map-editor-new-map = Nouvelle carte
button-map-editor-load-map = Charger une carte
dropdownbutton-news-bg-button = Actualités du champ de bataille
label-update-notice-a = Vous utilisez une version obsolète d'OpenRA.
label-update-notice-b = Téléchargez la dernière version sur www.openra.net
label-missions-title = Missions
label-multiplayer-title = Multijoueur
button-settings-title = Paramètres
label-mapchooser-panel-title = Choisir une carte
label-filter-order-controls-desc = Filtre :
label-filter-order-controls-desc-joiner = dans
label-filter-order-controls-orderby = Trier par :
button-mapchooser-panel-randommap = Carte aléatoire
button-mapchooser-panel-delete-map = Supprimer la carte
button-mapchooser-panel-delete-all-maps = Supprimer toutes les cartes
button-mapchooser-panel-ok = OK
button-missionbrowser-panel-start-briefing-video = Voir le briefing
button-missionbrowser-panel-stop-briefing-video = Arrêter le briefing
button-missionbrowser-panel-start-info-video = Voir la vidéo d'information
button-missionbrowser-panel-stop-info-video = Arrêter la vidéo d'information
button-missionbrowser-panel-play = Jouer
button-missionbrowser-panel-mission-info = Infos de mission
button-missionbrowser-panel-mission-options = Options
image-multiplayer-panel-password-protected-tooltip = Nécessite un mot de passe
image-multiplayer-panel-requires-authentication-tooltip = Nécessite un compte forum OpenRA
button-selected-server-join = Rejoindre
dropdownbutton-multiplayer-panel-filters = Filtrer les parties
button-multiplayer-panel-directconnect = IP directe
button-multiplayer-panel-create = Créer
checkbox-multiplayer-filter-panel-waiting-for-players = En attente
checkbox-multiplayer-filter-panel-empty = Vide
checkbox-multiplayer-filter-panel-password-protected = Protégé
checkbox-multiplayer-filter-panel-already-started = Commencé
checkbox-multiplayer-filter-panel-incompatible-version = Incompatible
label-multiplayer-createserver-panel-title = Créer un serveur
label-multiplayer-createserver-panel-server-name = Nom du serveur :
label-multiplayer-createserver-panel-password = Mot de passe :
label-multiplayer-createserver-panel-after-password = (optionnel)
label-multiplayer-createserver-panel-listen-port = Port :
checkbox-multiplayer-createserver-panel-advertise = Annoncer en ligne
label-notices-lan-advertising = - La partie sera annoncée uniquement sur le réseau local.
label-notices-lan-firewall = - Vous devez configurer manuellement votre pare-feu pour autoriser les connexions.
label-notices-lan-portforward-a = - Les joueurs peuvent se connecter via IP directe depuis Internet si vous
label-notices-lan-portforward-b = configurez manuellement la redirection de port sur votre routeur.
label-notices-no-upnp-advertising = - La partie sera annoncée sur le réseau local et Internet.
label-notices-no-upnp-firewall = - Vous devez configurer manuellement votre pare-feu pour autoriser les connexions.
label-notices-no-upnp-portforward-a = - Vous devez configurer manuellement votre routeur pour autoriser et rediriger
label-notices-no-upnp-portforward-b = les connexions vers votre IP locale et votre port.
label-notices-no-upnp-settings-a = - Vous pouvez activer UPnP/NAT-PMP (si pris en charge par votre routeur)
label-notices-no-upnp-settings-b = dans l'onglet Avancé du menu des paramètres.
label-notices-upnp-advertising = - La partie sera annoncée sur le réseau local et Internet.
label-notices-upnp-firewall = - Vous devez configurer manuellement votre pare-feu pour autoriser les connexions.
label-notices-upnp-portforward-a = - Le jeu configurera automatiquement la redirection de port.
label-notices-upnp-settings-a = - Vous pouvez désactiver UPnP/NAT-PMP dans le menu des paramètres.
button-multiplayer-createserver-panel-change-map = Changer de carte
button-multiplayer-createserver-panel-create = Créer
label-directconnect-panel-title = Se connecter au serveur
label-directconnect-panel-address = Adresse du serveur :
label-directconnect-panel-port = :
button-directconnect-panel-join = Rejoindre
button-profile-header-logout = Déconnexion
label-generate-keys-desc-a = Connectez-vous à un compte forum pour vous identifier
label-generate-keys-desc-b = auprès des autres joueurs, rejoindre des serveurs
label-generate-keys-desc-c = privés et afficher des badges.
button-generate-keys-key = Se connecter à un compte forum OpenRA
label-generating-keys-desc-a = Génération de la paire de clés d'authentification.
label-generating-keys-desc-b = Cela prendra quelques secondes...
label-register-fingerprint-desc-a = Une clé d'authentification a été copiée dans votre
label-register-fingerprint-desc-b = presse-papiers. Ajoutez-la à votre panneau de contrôle
label-register-fingerprint-desc-c = sur le forum OpenRA puis appuyez sur Continuer.
label-checking-fingerprint-desc-a = Récupération des détails du compte depuis
label-checking-fingerprint-desc-b = le forum OpenRA...
label-fingerprint-not-found-desc-a = Votre clé d'authentification n'est pas connectée
label-fingerprint-not-found-desc-b = à un compte forum OpenRA.
label-connection-error-desc-a = Échec de la connexion au forum OpenRA.
label-connection-error-desc-b = Veuillez vérifier votre connexion Internet.
label-replaybrowser-panel-title = Visionneuse de rediffusions
label-filters-title = Filtre
label-filters-flt-gametype-desc = Type :
dropdownbutton-filters-any = Tous
label-filters-flt-date-desc = Date :
label-filters-flt-duration-desc = Durée :
label-filters-flt-mapname-desc = Carte :
label-filters-flt-player-desc = Joueur :
dropdownbutton-filters-flt-player = N'importe qui
label-filters-flt-outcome-desc = Résultat :
label-filters-flt-faction-desc = Faction :
button-filters-flt-reset = Réinitialiser les filtres
label-management-manage-title = Gérer
button-management-mng-rensel = Renommer
button-management-mng-delsel = Supprimer
button-management-mng-delall = Tout supprimer
label-replay-list-container-replaybrowser-title = Choisir une rediffusion
button-replaybrowser-panel-watch = Regarder
label-network-section-header = Avancé
checkbox-nat-discovery-container = Activer la découverte UPnP/NAT-PMP
checkbox-fetch-news-container = Récupérer les actualités de la communauté
checkbox-perfgraph-container = Afficher le graphique de performance
checkbox-check-version-container = Vérifier les mises à jour
checkbox-perftext-container = Afficher le texte de performance
checkbox-sendsysinfo-container = Envoyer les informations système
label-sendsysinfo-checkbox-container-desc = Votre système d'exploitation, vos versions d'OpenGL et de .NET, ainsi que vos paramètres de langue seront envoyés avec un identifiant anonyme pour aider à prioriser le développement futur.
label-debug-section-header = Développeur
label-debug-hidden-container-a = Des options supplémentaires pour développeurs peuvent être activées via le
label-debug-hidden-container-b = paramètre Debug.DisplayDeveloperSettings ou l'option de lancement
checkbox-botdebug-container = Afficher les messages de débogage des IA
checkbox-checkbotsync-container = Vérifier la synchronisation autour du code BotModule
checkbox-luadebug-container = Afficher les messages de débogage des cartes
checkbox-checkunsynced-container = Vérifier la synchronisation autour du code non synchronisé
checkbox-replay-commands-container = Activer les commandes de débogage dans les rediffusions
checkbox-perflogging-container = Activer la journalisation des performances par tick
label-audio-section-header = Audio
label-no-audio-device-container = Les contrôles audio nécessitent un périphérique audio actif
checkbox-cash-ticks-container = Son de compteur d'argent
checkbox-mute-sound-container = Couper le son
label-sound-volume-container = Volume du son :
checkbox-mute-background-music-container =
    .label = Couper la musique du menu
    .tooltip = Couper la musique de fond lorsqu'aucune piste spécifique n'est en lecture
label-music-title-volume-container = Volume de la musique :
label-audio-device-container = Périphérique audio :
label-video-volume-container = Volume des vidéos :
label-restart-required-container-audio-desc = Les changements de périphérique seront appliqués après le redémarrage du jeu
checkbox-hide-replay-chat-container = Masquer le chat dans les rediffusions
label-target-lines-dropdown-container = Lignes de cible :
label-status-bar-dropdown-container-bars = Barres de statut :
checkbox-player-stance-colors-container =
    .label = Couleurs selon les relations entre joueurs
    .tooltip = Changer les couleurs des joueurs selon la relation (soi, ennemi, allié, neutre)
checkbox-ui-feedback-container =
    .label = Afficher les notifications de l'interface
    .tooltip = Afficher des notifications textuelles temporaires pour les événements de l'interface
checkbox-transients-container =
    .label = Afficher les notifications d'événements de jeu
    .tooltip = Afficher des notifications textuelles temporaires pour les événements de jeu
checkbox-pause-shellmap-container = Mettre en pause l'arrière-plan du menu
label-video-section-header = Vidéo
label-video-mode-dropdown-container = Mode vidéo :
dropdownbutton-video-mode-dropdown-container = Fenêtré
label-window-resolution-container-size = Taille de la fenêtre :
label-window-resolution-container-x = x
label-display-selection-container = Sélectionner l'écran :
dropdownbutton-display-selection-container-dropdown = Standard
checkbox-vsync-container = Activer la synchronisation verticale
checkbox-frame-limit-gamespeed-container = Limiter le framerate au taux de tick du jeu
label-gl-profile-dropdown-container = Profil OpenGL :
label-restart-required-container-video-desc = Les changements d'affichage et d'OpenGL nécessitent un redémarrage
label-hotkeys-panel-filter-input = Filtrer par nom :
label-hotkeys-panel-context-dropdown = Contexte :
label-hotkey-empty-list-message = Aucun raccourci ne correspond aux critères de filtre.
label-notices-readonly-notice = Ce raccourci ne peut pas être modifié
button-hotkey-remap-dialog-override = Remplacer
button-hotkey-remap-dialog-clear =
    .label = Effacer
    .tooltip = Supprimer le raccourci
button-hotkey-remap-dialog-reset =
    .label = Réinitialiser
    .tooltip = Rétablir par défaut
label-zoom-modifier-container = Modificateur de zoom :
checkbox-alternate-scroll-container = Défilement souris alternatif
checkbox-lockmouse-container = Verrouiller la souris dans la fenêtre
label-mouse-scroll-type-container = Comportement du défilement :
label-scrollspeed-slider-container-scroll-speed = Vitesse de défilement :
label-zoomspeed-slider-container-zoom-speed = Vitesse de zoom :
label-ui-scrollspeed-slider-container-scroll-speed = Vitesse de défilement de l'interface :
button-settings-panel-reset = Réinitialiser
label-latency-tooltip-prefix = Latence :
label-anonymous-player-tooltip-name = Joueur anonyme
label-game-admin = Administrateur de partie
label-gamesave-loading-screen-title = Chargement de la partie sauvegardée
label-gamesave-loading-screen-desc = Appuyez sur Échap pour annuler le chargement et revenir au menu principal
