checkbox-fog-of-war =
    .label = Brouillard de Guerre
    .description = La ligne de vue est nécessaire pour voir les forces ennemies
checkbox-explored-map =
    .label = Carte explorée
    .description = Le brouillard de guerre initial est révélé
checkbox-debug-menu =
    .label = Menu de débogage
    .description = Active les commandes de triche et de développeur
checkbox-crates =
    .label = Caisse
    .description = Collectez des caisses avec des unités pour recevoir des bonus ou des pénalités aléatoires
checkbox-ally-build-radius =
    .label = Construire près des alliés
    .description = Permet aux alliés de placer des structures dans votre zone de construction
checkbox-build-radius =
    .label = Limiter la zone de construction
    .description = Limite le placement des structures aux zones autour des chantiers de construction
checkbox-short-game =
    .label = Partie courte
    .description = Les joueurs sont vaincus lorsque leurs bases sont détruites
dropdown-tech-level =
    .label = Niveau technologique
    .description = Les unités et capacités que les joueurs peuvent utiliser
dropdown-game-speed =
    .label = Vitesse de jeu
    .description = La vitesse à laquelle le temps s'écoule
checkbox-separate-team-spawns =
    .label = Points d'apparition séparés par équipe
    .description = Les joueurs sans points d'apparition assignés démarreront aussi loin que possible des joueurs ennemis
dropdown-starting-units =
    .label = Unités de départ
    .description = Les unités avec lesquelles les joueurs commencent la partie
dropdown-time-limit =
    .label = Limite de temps
    .description = Le joueur ou l'équipe avec le meilleur score après ce temps gagne
label-tooltip-prefix =
    .ally = Allié
    .enemy = Ennemi
